### ISSUE TITLE
AngularJointDrive going crazy when is child of moving object

### ISSUE THREAD

**Issue by tanjunior** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#207]
### Environment

* Code source: https://www.vrtk.io/tilia.html
* Code version: 2.5.8
* Platform version: Unity 2019.3.15f1
* 3rd party dependencies:

### Steps to reproduce
create a vehicle following this https://docs.unity3d.com/Manual/WheelColliderTutorial.html
create a lever following this https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/tree/master/Documentation/HowToGuides/CreatingALever
Add lever as a child of a the vehicle
Drive the vehicle.

### Expected behavior

Lever should stay in place and the position should stay as it was adjusted to

### Current behavior

Lever shift by itself and bounce around

**Comment by thestonefox** [comment]
This isn't a bug. It seems you're childing a physics joint object to another object that is being moved by physics, which is going to cause conflicts in your game physics, which is why you're seeing the lever move by itself.

You're better off using a TransformDrive for the lever if you want the parent to be controlled by physics and then those physics won't interfere with the child drive as it is not physics based.

**Comment by tanjunior** [comment]
@thestonefox thank you. I will try it right now. I believe that I can set up a lever using TransformDrive the same way using AngularDrive
