### ISSUE TITLE
Request for a 'Show Interactable' button

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Interactions.Controllables.Unity#49]
## Is your feature request related to a problem?

In order to access the Interactable inside a linear/angular drive, we have to manually navigate in the hierarchy.

## Describe the solution you'd like

a 'Show Interactable' button when clicked to select the underlying interactable.

## Additional context

below is the 'Show Mesh Container' button in Interactable facade
I would expect a similar layout/button for the drive's 'Show Interactable' button
![image](https://user-images.githubusercontent.com/22952143/87419002-49972600-c605-11ea-9de0-0029ddb1e37e.png)

**Comment by thestonefox** [comment]
May be worth actually having a component that you attach that does this kind of lookup. Otherwise everything ends up needing a custom inspector.

The component could be a simple zinnia component that you give it a target GameObject, and it uses a custom inspector to display a button that you click and it basically shows the target

**Comment by bddckr** [comment]
A component is a thing you need at runtime, so I think this warrants a custom editor that can be shown in its own window instead. This could then automatically adapt to the current selection changing and even show the target right there in the same window. (The button then would just select the target.)

**Comment by thestonefox** [comment]
but how do you define the target?

For example on  a DriveFacade you want the button to highlight and expand down to the Interactable child.

You need some way of saying "this is the Target" and then that thing wrapped in a custom inspector to show a button that says "Click here to Show <Target>" and you click it and it does the hierarchy expand and gameobject select thing (like the show mesh container does)

You could then apply this component to the prefab elements and hook them up.

**Comment by bddckr** [comment]
I was just thinking the editor window implementation would know about these things, but was forgetting about the issue with all the packages 😅

Just saying: Adding a component that only is to be used at edit time feels very wrong?

What's wrong with the drive in that example offering such a button in a custom inspector for the drive? It might still piggy back on some implementation that is reusable and is shared among other custom inspectors? I guess that is what you're suggesting, just with a separate component and some (I assume) `GetComponent` based communication that happens automatically in the editor when it sees that helper component for this editor-only need?

**Comment by thestonefox** [comment]
I don't like the idea of having custom inspectors because they're limited (such as you can't do multi selecting on custom fields) not that this would be an issue here, but the ability to have this "expose inner guts" concept could be useful in lots of places and that means loads of custom inspectors (which is horrid imho).

I wonder if we could have some sort of custom inspector window that you can also describe a config file for it.

E.g. 

I select a GameObject that contains a DriveFacade
Controllables/Runtime contains some sort of config file (e.g. yaml) that says DriveFacade > GO-Path-To-Interactable

Then the custom inspector window goes "ok you've selected a DriveFacade, I have a config on how to deal with that, so i'll render a button that goes to the target you configured"

**Comment by thestonefox** [comment]
(I also agree that having GameObject components for helping in the editor is also a horrible idea)

**Comment by thestonefox** [comment]
resolved with https://github.com/ExtendRealityLtd/Tilia.Interactions.Controllables.Unity/pull/87
